language: python
python:
- 3.8
- 3.7
- 3.6

before_install:
- pip install -U pip setuptools wheel tox-travis

install:
- pip install -r ./requirements_dev.txt

branches:
  only:
  - master

script:
- python setup.py sdist
- python setup.py bdist_wheel
- twine check dist/*
- tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: pix666
  password:
    secure: Vn0QqcCpZYE5dcQbPP/VdNSB6t1iGvPgrsyPv1BV9Rhgw4sNLsEzCPGMmOYIcxFS5sPSwsKBN1PvBz8+54K+Kal3s0GPuy6y6Lue1COKoe+WgJtPDBt6E9Qb8TeeXlu3z+2yvGQutj0t9FvgN/SCkKAtqbWAVm2O4LCfgR0TT5LjaXKd9GZy3Fa9nlNJ+fOcdYADA6FqbYin1pocqyf4tyioxDgnUcAwMibje4REQiPFiapHjAoffXHbV29E7FjE4o8jkC0igD26d4sIrbhBkfbp2sVzlcUPo89jMmfCc+2TpXvW6pSjhV43Vk980lbHh+nORR6ch3SU/9gzePXnPZktailDlBpwJmgLDbKyFQ+kV6/FHNuKUPFA2YagO8cX7F6kA72GttOEpQKp53KUFvBBZnM+QSBzYLEAW4ryPqiWkol0DHEQaNh6iVdsxUQEQqXiQ4GaRelKJt7A+KKtfS59ToR/dx+SI3TUsT3pIvMCQ2+lxWuclZM6CGK5rBCgEZELTbX2zuWs5+spHScixigYAsvuc01DjOLQn1yMgqad/Kqg926T4u61wh1PPGPtOvTF+Be7GOdH7G7Rh3zRUUntoEQ4lKtfdVJiUy6cw5vgjUmGzm6yRdj+pXG0adC1yrbNMnNcmWFF/hqj9ZCFj3yVw4ayQ23jFkH6YNESZ+8=
  on:
    repo: dldevinc/django-flatly
    tags: true
